language: node_js
node_js:
  - "node"
cache: npm
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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
  local_dir: dist
  on:
    branch: master
